### ISSUE TITLE
Padding Issue on Counter Element

### ISSUE THREAD

**Issue by ibweb** [forrestkirby/herzogdupont-joomla#26]
The counter element does not allow for proper padding  and/or breaks.  
Even if we resize the radius larger (thinking the text was too long for the counter), the padding will still overlap the radius. 

See https://www.swiftprint.com/sustainability as an example.

**Comment by forrestkirby** [comment]
Hi ibweb,

please try to add the following CSS rule in the field *Advanced 🠖 CSS* of your counter element (adjust the values to your needs):

```css
.el-element .uk-position-center {
    padding: 0px 20px;
}
```

Kind regards
